### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by pstachula-dev** [aurorascharff/next15-filterlist#2]
Will it be possible to see some unit tests in Vitest/Jest?

Inspired by the presentation from the conference, I created an application, unfortunately I am not able to test it. Because I have such errors:
```sh
TypeError: (0 , _react.use) is not a function
```

**Comment by aurorascharff** [comment]
Right! You can try using this article to test those React 19 things :) Basically you need to enforce your React version and use suspense around the component using `use`.

https://aurorascharff.no/posts/running-tests-with-rtl-and-vitest-on-internationalized-react-server-components-in-nextjs-app-router/

I will think about adding some!

**Comment by pstachula-dev** [comment]
Thanks! 

I checked all problems, but I still have same error.
It looks like Next.js implicitly replace the React version.

In the application everything works perfectly, but I have only issue with tests. 
For Jest `React.use` dosen't exits.

My project uses:
```json
"next": "^14.2.6",
"react": "18.3.1",
"react-dom": "18.3.1",
```

**Debug in tests:**

```sh
console.log({ ver: React.version, use: React.use });

=> console.log
    { ver: '18.3.1', use: undefined }
```


**Debug same component in Next.js:**
```sh

=> console..log
     {ver: '18.3.0-canary-14898b6a9-20240318', use: ƒ}
```

**Comment by aurorascharff** [comment]
You need to have react 19 to test use(). Or, you can mock it globally.

Correct, next.js does some weird stuff with the react version.

"If the method is failing, make sure you are using the correct React version in your tests. You can check it by throwing a console.log(React.version) into a test. If it is not using React 19, run npm install react@rc react-dom@rc again (even though you already have React RC in your dependencies)."

**Comment by pstachula-dev** [comment]
Ok actually, after installing react-19-rc tests and the application works fine. 🥹 

However, this involves installing packages with the `npm i --force` flag, because `@testing-library` and many more libraries requiers peerDependency of react-18

**Comment by aurorascharff** [comment]
Yes, force install is needed anyway i think as mentioned in the README ☺️
Good thing you got it working!
